FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

# Update sistem
RUN apt-get update && apt-get install -y \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Clone Kohya
RUN git clone https://github.com/bmaltais/kohya_ss.git /workspace/kohya_ss

# Set working directory
WORKDIR /workspace/kohya_ss

# Install dependencies dasar dulu
RUN pip install --upgrade pip && \
    pip install \
    gradio \
    altair \
    easygui \
    huggingface-hub \
    toml \
    voluptuous

CMD ["/bin/bash"]
